version: "3.5"

services:
  cardano-node:
    image: inputoutput/cardano-node:1.26.2
    environment:
      - NETWORK=${NETWORK:-mainnet}
    volumes:
      - ${HOME}/.cardano/${NETWORK}:/data
      - node-ipc:/ipc
      - node-config:/nix/store
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  cardano-wallet:
    image: inputoutput/cardano-wallet:2021.4.28
    volumes:
      - ${HOME}/.cardano/wallet-${NETWORK}:/wallet-db
      - node-ipc:/ipc
      - node-config:/config
    ports:
      - 8090:8090
    entrypoint: []
    command: bash -c "
      ([[ $$NETWORK == \"mainnet\" ]] && $$CMD --mainnet) ||
      ([[ $$NETWORK == \"mainnet_candidate*\" ]] && $$CMD --staging /config/*-$$NETWORK-byron-genesis.json) ||
      ($$CMD --testnet /config/*-$$NETWORK-byron-genesis.json)
      "
    environment:
      CMD: "cardano-wallet serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0"
      NETWORK:
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      -  /home/giovanni/.cardano/postgresql-${NETWORK:-mainnet}:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-db-sync:
    image: inputoutput/cardano-db-sync:9.0.0
    environment:
      - NETWORK=${NETWORK:-mainnet}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - cardano-node
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - /home/giovanni/.cardano/cdb-sync-${NETWORK:-mainnet}:/var/lib/cdbsync
      - node-ipc:/node-ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

secrets:
  postgres_db:
    file: ./config/secrets/postgres_db
  postgres_password:
    file: ./config/secrets/postgres_password
  postgres_user:
    file: ./config/secrets/postgres_user

volumes:
  node-ipc:
  node-config:
